In [ ]:
"""
MOVIE RECOMMENDATION SYSTEM

YBI Foundation Internship Project

Submitted By:
Karri Vinay

Technology:
Python, Machine Learning, Recommendation Systems
"""

'\nMOVIE RECOMMENDATION SYSTEM\n\nYBI Foundation Internship Project\n\nSubmitted By:\nKarri Vinay\n\nTechnology:\nPython, Machine Learning, Recommendation Systems\n'

In [ ]:
# Import Required Libraries

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving tmdb_5000_movies.csv.zip to tmdb_5000_movies.csv.zip
Saving tmdb_5000_credits.csv.zip to tmdb_5000_credits.csv.zip

In [ ]:
import os

os.listdir()

['.config',
 'tmdb_5000_credits.csv.zip',
 'tmdb_5000_movies.csv.zip',
 'sample_data']

In [ ]:
import zipfile

with zipfile.ZipFile('tmdb_5000_movies.csv.zip', 'r') as zip_ref:
    zip_ref.extractall()

with zipfile.ZipFile('tmdb_5000_credits.csv.zip', 'r') as zip_ref:
    zip_ref.extractall()

print("Files Extracted Successfully")

Files Extracted Successfully

In [ ]:
import os

os.listdir()

['.config',
 'tmdb_5000_credits.csv.zip',
 'tmdb_5000_movies.csv',
 'tmdb_5000_movies.csv.zip',
 'tmdb_5000_credits.csv',
 'sample_data']

In [ ]:
import pandas as pd

movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

print("Movies Dataset Shape:", movies.shape)
print("Credits Dataset Shape:", credits.shape)

Movies Dataset Shape: (4803, 20)
Credits Dataset Shape: (4803, 4)

In [ ]:

credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [ ]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [ ]:
movies = movies.merge(credits, on='title')

movies.shape

(4809, 23)

In [ ]:
movies = movies[['movie_id',
                 'title',
                 'overview',
                 'genres',
                 'keywords',
                 'cast',
                 'crew']]

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [ ]:
movies.dropna(inplace=True)

movies.shape

(4806, 7)

In [ ]:
import ast

In [ ]:
def convert(text):
    L = []

    for i in ast.literal_eval(text):
        L.append(i['name'])

    return L

In [ ]:
movies['genres'] = movies['genres'].apply(convert)

movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
movies['keywords'] = movies['keywords'].apply(convert)

In [ ]:
def convert_cast(text):

    L = []

    counter = 0

    for i in ast.literal_eval(text):

        if counter != 3:

            L.append(i['name'])

            counter += 1

        else:
            break

    return L

In [ ]:
movies['cast'] = movies['cast'].apply(convert_cast)

In [ ]:
def fetch_director(text):

    L = []

    for i in ast.literal_eval(text):

        if i['job'] == 'Director':

            L.append(i['name'])

            break

    return L

In [ ]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [ ]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [ ]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [ ]:
movies['genres'] = movies['genres'].apply(
    lambda x:[i.replace(" ","") for i in x])

movies['keywords'] = movies['keywords'].apply(
    lambda x:[i.replace(" ","") for i in x])

movies['cast'] = movies['cast'].apply(
    lambda x:[i.replace(" ","") for i in x])

movies['crew'] = movies['crew'].apply(
    lambda x:[i.replace(" ","") for i in x])

In [ ]:
movies['tags'] = (
    movies['overview']
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['crew']
)

In [ ]:
new_df = movies[['movie_id','title','tags']]

In [ ]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

/tmp/ipykernel_968/3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [ ]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

/tmp/ipykernel_968/3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [ ]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [ ]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [ ]:
def stem(text):

    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [ ]:
new_df['tags'] = new_df['tags'].apply(stem)

/tmp/ipykernel_968/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(
    max_features=5000,
    stop_words='english'
)

vectors = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
vectors.shape

(4806, 5000)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [ ]:
similarity.shape

(4806, 4806)

In [ ]:
movies['cast'] = movies['cast'].apply(
    lambda x:[i.replace(" ","") for i in x]
)

In [ ]:
def recommend(movie):

    matches = new_df[
        new_df['title'].str.contains(movie, case=False, na=False)
    ]

    if len(matches) == 0:
        print("Movie not found!")
        return

    movie_title = matches.iloc[0]['title']

    index = new_df[new_df['title'] == movie_title].index[0]

    distances = similarity[index]

    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x:x[1]
    )

    print(f"\nRecommendations for {movie_title}:\n")

    for i in movie_list[1:11]:
        print(new_df.iloc[i[0]].title)
def movies_by_actor(actor_name):

    actor_name = actor_name.replace(" ", "").lower()

    result = movies[
        movies['cast'].apply(
            lambda cast:
            any(
                actor_name in actor.lower()
                for actor in cast
            )
        )
    ]

    return result[['title']]

In [ ]:
movie_name = input("Enter Movie Name: ")

recommend(movie_name)

Enter Movie Name: life

Recommendations for Life of Pi:

Sahara
Silver Medalist
Deep Rising
Crouching Tiger, Hidden Dragon
Two Brothers
The Blue Lagoon
Redemption Road
Arn: The Knight Templar
Pirates of the Caribbean: At World's End
The Indian in the Cupboard

In [ ]:
new_df.to_csv(
    'processed_movies.csv',
    index=False
)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [ ]:
print("Total Movies:", len(new_df))
print("Vocabulary Size:", len(cv.get_feature_names_out()))

Total Movies: 4806
Vocabulary Size: 5000

In [ ]:
print("""
==================================
MOVIE RECOMMENDATION SYSTEM
==================================

Dataset : TMDB 5000
Movies : 4800+
Technique : Content-Based Filtering
Vectorization : CountVectorizer
Similarity Measure : Cosine Similarity

Project Completed Successfully
==================================
""")

==================================
MOVIE RECOMMENDATION SYSTEM
==================================

Dataset : TMDB 5000
Movies : 4800+
Technique : Content-Based Filtering
Vectorization : CountVectorizer
Similarity Measure : Cosine Similarity

Project Completed Successfully
==================================

In [ ]:
import pickle

pickle.dump(
    similarity,
    open('similarity.pkl','wb')
)

In [ ]:
pickle.dump(
    new_df,
    open('movies.pkl','wb')
)

In [ ]:
pickle.dump(
    cv,
    open('vectorizer.pkl','wb')
)

In [ ]:
import os

os.listdir()

['.config',
 'similarity.pkl',
 'tmdb_5000_credits.csv.zip',
 'vectorizer.pkl',
 'tmdb_5000_movies.csv',
 'tmdb_5000_movies.csv.zip',
 'movies.pkl',
 'tmdb_5000_credits.csv',
 'processed_movies.csv',
 'sample_data']

In [ ]:
from google.colab import files

files.download('movies.pkl')
files.download('similarity.pkl')
files.download('vectorizer.pkl')

In [ ]:
print("Total Movies:", len(new_df))
print("Vocabulary Size:", len(cv.get_feature_names_out()))
print("Similarity Matrix Shape:", similarity.shape)

Total Movies: 4806
Vocabulary Size: 5000
Similarity Matrix Shape: (4806, 4806)

In [ ]:
recommend("avengers")

Recommendations for Avengers: Age of Ultron:

Iron Man 3
Iron Man 2
Iron Man
Thor
The Avengers
The Wolverine
Captain America: Civil War
Ant-Man
Thor: The Dark World
X-Men Origins: Wolverine

In [ ]:
new_df.to_csv('movies.csv', index=False)

In [ ]:
from google.colab import files
files.download('movies.csv')

In [ ]:
import numpy as np

np.save('similarity.npy', similarity)

In [ ]:
from google.colab import files
files.download('similarity.npy')

In [ ]:
similarity = np.load('similarity.npy')

In [ ]:
import numpy as np

np.save('similarity.npy', similarity)

print("Saved Successfully")

Saved Successfully

In [ ]:
from google.colab import files

files.download('similarity.npy')